# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0216d19aac5cb32c4e3b9964fdda930767bfc2939921468d1f8998e9e4b741356574ea54d9e59c299caa9a562eb1b743eb9a0221eaf31a04d1548ddf1dcd4516

test:
  secret_key_base: e785b6615f7f3cec81bc5b59d90aeaf40027dd529e8440cbc14bd18feac074a48fb0d8db3a6ab05419298a0b81a2e72ba69a3b27feb8ce60cf6874998c147c78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
